baseURL = "https://www.innervoicepower.com"
languageCode = "en-us"
title = "Inner Voice Coaching"
disableKinds = ["taxonomy"]
enableRobotsTXT = "true"
summaryLength = 30
copyright = "Béa Beaudry"
[params]
  description = "Where Your Power Resides"
  logo = "android-chrome-192x192.png"
  donation_url = ""
  contact = ""
  copyrighturl = "https://www.innervoicepower.com"
  address1 = ""
  address2 = ""
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menus]

  [[menus.main]]
    name = "About Me"
    url = "/about/"
    weight = 20

  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 10

  [[menus.main]]
    name = "Fee Schedule"
    url = "/fees/"
    weight = 11

  [[menus.main]]
    name = "Booking"
    url = "#"
    weight = 12

  [[menus.main]]
    name = "Coaching Session"
    pageRef = "/book/coaching/"
    parent = "Booking"
    weight = 1

  [[menus.main]]
    name = "Dream Analysis"
    pageRef = "/book/dream-analysis/"
    parent = "Booking"
    weight = 2